version: 2

models:
  - name: users_dbt_model
    description: "A starter User dbt model"
    columns:
      - name: legacy_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
